sudo: required
language: ruby
rvm:
  - 2.2.3
env:
  global:
    - DB=postgresql
    - RAILS_ENV=test
    - CI_NODE_TOTAL=1
    - PGPORT=5432
    - PGHOST=localhost
  matrix:
    - CI_NODE_INDEX=0
before_install:
  - gem install bundler -v 1.11.2
services:
  - postgresql
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
    - libcurl3
    - libcurl3-gnutls
    - libcurl4-openssl-dev
  postgresql: 9.5
bundler_args: --jobs=1 --retry=3 --deployment --without development
before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart

script:
  - bundle exec rake pm:test:prepare
  - bundle exec rspec
