sudo: false
dist: trusty
language: ruby
rvm:
  - 2.4.0
  - 2.2.3
env:
  global:
    - DB=postgresql
    - RAILS_ENV=test
    - CI_NODE_TOTAL=1
    - PGPORT=5432
    - PGHOST=localhost
  matrix:
    - CI_NODE_INDEX=0
before_install:
  - rvm rubygems latest
  - gem install bundler
services:
  - postgresql
addons:
  postgresql: "9.5"
bundler_args: --jobs=1 --retry=3
script:
  - bundle exec rake pm:test:prepare
  - bundle exec rspec
